import os
import json
import google.generativeai as genai

# --- 1. CONFIGURE THE GEMINI CLIENT ---
# This line reads the GEMINI_API_KEY from your .env file
# (which main.py will load)
gemini_api_key = os.environ.get("GEMINI_API_KEY") or os.environ.get("GOOGLE_API_KEY")
if not gemini_api_key:
    raise ValueError("GEMINI_API_KEY or GOOGLE_API_KEY must be set in environment variables")
genai.configure(api_key=gemini_api_key)

# --- 2. CREATE YOUR "SPECIALIST" MODELS ---

# Specialist 1: The "AI Analyst"
# This model has a system prompt and will return JSON.
ai_analyst_prompt = """
You are an expert AI text detection specialist. Your task is to determine if the provided text was generated by an AI (like ChatGPT, Gemini, etc.) or written by a human.

Analyze the text for these specific indicators of AI generation:

1. **Repetitive patterns**: AI often uses similar sentence structures repeatedly
2. **Overly formal or perfect language**: AI text tends to be more polished and formal than human writing
3. **Lack of personal voice or unique style**: AI text lacks individual writing quirks
4. **Consistent sentence length**: AI often produces sentences of similar length
5. **Generic transitions**: Phrases like "Furthermore", "Moreover", "In conclusion" used excessively
6. **Lack of typos or natural errors**: Human writing has occasional mistakes
7. **Too structured**: AI text is often overly organized and logical
8. **Vocabulary patterns**: AI may use certain words or phrases more frequently
9. **Lack of colloquialisms or informal language**: AI tends to be more formal
10. **Perplexity**: AI-generated text has lower perplexity (more predictable word choices)

The text may be in Norwegian or English. Analyze it carefully.

Provide your assessment as a JSON object with two keys:
1. "likelihood": A string (one of "Very Low", "Low", "Medium", "High", "Very High")
   - "Very High" or "High" = Strongly indicates AI generation
   - "Medium" = Could be either, but leans toward AI
   - "Low" or "Very Low" = Appears to be human-written
2. "reasoning": A detailed 2-3 sentence explanation describing the specific patterns you found that led to your conclusion. Be specific about what made you classify it this way.
"""

# Use a more capable model for better AI detection
ai_analyst_model = genai.GenerativeModel(
    'gemini-2.5-flash-preview-09-2025',
    system_instruction=ai_analyst_prompt
)

# Specialist 2: The "Web Researcher"
# This model has a system prompt and will return JSON.
web_researcher_prompt = """
You are an expert plagiarism detection specialist. Your task is to identify if the provided text has been copied or heavily paraphrased from online sources.

The text may be in Norwegian or English. Analyze it carefully for:

1. **Exact or near-exact matches**: Look for phrases, sentences, or paragraphs that appear verbatim or with minor changes from common online sources
2. **Common knowledge vs. copied content**: Distinguish between general knowledge and specific copied passages
3. **Recognizable patterns**: Identify text that matches typical online article structures, Wikipedia entries, news articles, blog posts, or educational content
4. **Specific facts or statistics**: If the text contains specific data, quotes, or statistics, these may be copied from sources
5. **Stylistic matches**: Text that matches the writing style of common online sources (news articles, Wikipedia, educational sites)

IMPORTANT: You have access to a vast knowledge base. Use your training data to identify if this text matches content from:
- Wikipedia articles
- News websites
- Educational websites
- Blogs and online articles
- Academic sources
- Government websites
- Any other online publications

If you recognize the text or parts of it as matching known online sources, provide those sources.

Return a JSON object with one key: "sources".
"sources" should be an array of objects. Each object must have:
1. "url": The source URL (if you know it, otherwise use a placeholder like "https://example.com/article" or the domain if known)
2. "title": The page/article title (if you recognize it, otherwise describe the type of source)
3. "snippet": A quote from the text that matches the source (the actual matching text from the user's input)

If the text appears to be original and not copied from online sources, return an empty "sources" array: { "sources": [] }

Be thorough - if you recognize ANY part of the text as potentially copied, include it in the sources array.
"""

# Use a more capable model with better knowledge base for plagiarism detection
web_researcher_model = genai.GenerativeModel(
    'gemini-2.5-flash-preview-09-2025',
    system_instruction=web_researcher_prompt
)

# Shared config for both models to ensure they return JSON
generation_config = genai.GenerationConfig(response_mime_type="application/json")


# --- 3. DEFINE THE FUNCTIONS MAIN.PY WILL CALL ---

async def analyze_ai_likelihood(text: str) -> dict:
    """
    Calls the AI Analyst model.
    Uses generate_content_async for non-blocking performance.
    """
    try:
        # Create a more detailed prompt for better analysis
        analysis_prompt = f"""Analyze the following text to determine if it was AI-generated or human-written:

{text}

Provide a thorough analysis focusing on the specific indicators mentioned in your instructions."""
        
        response = await ai_analyst_model.generate_content_async(
            analysis_prompt, 
            generation_config=generation_config
        )
        # Parse the JSON string from the model's response
        result = json.loads(response.text)
        print(f"AI Analysis result: {result}")
        return result
    except json.JSONDecodeError as e:
        print(f"JSON decode error in AI analysis: {e}")
        print(f"Raw response: {response.text if 'response' in locals() else 'No response'}")
        # Try to extract likelihood from text if JSON parsing fails
        return {"likelihood": "Medium", "reasoning": "Analysis completed but response format was unexpected."}
    except Exception as e:
        print(f"Error in AI analysis: {e}")
        # Return a structured error
        return {"likelihood": "Medium", "reasoning": f"Analysis service encountered an error: {str(e)}"}

async def find_online_plagiarism(text: str) -> dict:
    """
    Calls the Web Researcher model.
    Uses generate_content_async for non-blocking performance.
    """
    try:
        # Create a more detailed prompt for better plagiarism detection
        plagiarism_prompt = f"""Analyze the following text to identify if it has been copied or heavily paraphrased from online sources:

{text}

Be thorough in your analysis. Check if you recognize this text or parts of it from:
- Wikipedia articles
- News websites and articles
- Educational websites
- Blogs and online publications
- Academic sources
- Any other online sources

If you find matches, provide the sources with URLs, titles, and matching snippets."""
        
        response = await web_researcher_model.generate_content_async(
            plagiarism_prompt, 
            generation_config=generation_config
        )
        # Parse the JSON string from the model's response
        result = json.loads(response.text)
        print(f"Plagiarism detection result: {result}")
        return result
    except json.JSONDecodeError as e:
        print(f"JSON decode error in plagiarism detection: {e}")
        print(f"Raw response: {response.text if 'response' in locals() else 'No response'}")
        # Return empty sources if JSON parsing fails
        return {"sources": []}
    except Exception as e:
        print(f"Error in web search: {e}")
        # Return empty sources on error
        return {"sources": []}